### PR TITLE
dplyr::build_sql as a recommended tranform_function for SQL templating

### PR DESCRIPTION
**Pull request by zachmayer**

### CODE REVIEW

**Comment by zachmayer** [comment]
Should be sufficient to close https://github.com/Bart6114/infuser/issues/2

**Comment by Bart6114** [comment]
This (https://github.com/zachmayer/infuser/commit/26cbaff786a5db64436aab64de6240b294a5e90d?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) would produce the following SQL: 

```INSERT INTO Students (Name) VALUES (''Robert''); DROP TABLE Students;--'')``` 

Which isn't valid SQL and would produce an error. Is this a good example to show here? Now the code is safe, but only due to the fact that it errors out?

**Comment by zachmayer** [comment]
I updated the example to use the inputs in the `?dplyr::build_sql` example, which produces: `INSERT INTO Students (Name) VALUES ('Robert''); DROP TABLE Students;--')`

See also `?dplyr::escape`.

**Comment by Bart6114** [comment]
I don't want to be too nit picky :) but wouldn't the 'unwanted' output give an error now? instead of dropping the table?

https://github.com/zachmayer/infuser/commit/ab8b5e0cba6bd9672b6a771428aaff29b5e08eaf#diff-04c6e90faac2675aa89e2176d2eec7d8R114

**Comment by zachmayer** [comment]
Pick away!  See next commit

**Comment by zachmayer** [comment]
Coveralls seems stalled.  You could re-start the travis build, and maybe it will re-hit coveralls.

**Comment by Bart6114** [comment]
Thanks for the PR! Merged it with some minor adjustments (see readme file).

**Comment by zachmayer** [comment]
:+1:

**Pull request merged**
